version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: chess
      RABBITMQ_DEFAULT_PASS: chess123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"

  api:
    build: .
    container_name: chess-api
    ports:
      - "5000:8080"
    depends_on:
      - rabbitmq
    environment:
      DYNAMODB_URL: localhost:8000
      RABBITMQ_URL: localhost:15672
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: chess
      RabbitMQ__Password: chess123

volumes:
  rabbitmq_data: